version: '3.5'

services:

  db:
    image: mysql
    container_name: mysql-server
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  cache:
    image: redis
    container_name: cache-server
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  backend:
    build: .
    container_name: backend-server
    depends_on:
      - cache
      - db
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
      - TYPEORM_HOST=host.docker.internal
      - REDIS_CLUSTER_MODE=false
      - REDIS_KEY_PREFIX=CVEVOSKA_
      - REDIS_CONNECTION_STRING=127.0.0.1:6380
      - TYPEORM_PORT=3306
      - ALLOW_CORS=true
      - ACCESS_CONTROL_ALLOW_ORIGIN=http://localhost:4200
      - SESSION_SECURE=false # only for local, use `true` if start for production (https)
volumes:
  cache:
    driver: local

