version: '3.5'

volumes:
  db-volumes:
    driver: local
  cache:

services:
  db:
    image: mysql
    container_name: mysql-server
    restart: always
    ports:
     - 172.17.0.1:3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_TCP_PORT: 3307
    volumes:
    - db-volumes:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  cache:
    image: redis
    container_name: cache-server
    restart: always
    ports:
      - 172.17.0.1:6379:6379
    volumes:
      - cache:/data

  backend:
    image: chevoska/testapp:server_1_1
    # build: ./chevoska-server
    container_name: server
    depends_on:
      - cache
      - db
    ports:
      - 172.17.0.1:3001:3001
    volumes:
      - /var/chevoska/uploads:/usr/src/app/public/uploads
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - NODE_ENV=development
      - STORAGE_DIR=/usr/src/app/public/


      - TYPEORM_HOST=db
      - TYPEORM_PORT=3307
      - CUSTOM_HOST=http://192.168.88.8:80

      - REDIS_CLUSTER_MODE=false
      - REDIS_KEY_PREFIX=CVEVOSKA_
      - REDIS_CONNECTION_STRING=cache:6379

      - ALLOW_CORS=true
      - ACCESS_CONTROL_ALLOW_ORIGIN=http://192.168.88.8:4202,http://192.168.88.8
      - SESSION_SECURE=false # only for local, use `true` if start for production (https)
