export enum PasswordRecoveredSteps {
  SEND_EMAIL_STEP = 'SEND_EMAIL_STEP',
  RESET_PASSWORD_STEP = 'RESET_PASSWORD_STEP',
  CHANGE_PASSWORD_STEP = 'CHANGE_PASSWORD_STEP',
  SUCCESS_RECOVER = 'SUCCESS_RECOVER',
  ERROR_RECOVER = 'ERROR_RECOVER',
}
